name: Renovate

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
          - info
          - debug
          - trace
  
  # Scheduled runs
  schedule:
    # Run every Monday at 06:00 UTC (07:00/08:00 Berlin time depending on DST)
    - cron: '0 6 * * 1'
  
  # Run on pushes to renovate config
  push:
    paths:
      - '.github/workflows/renovate.yml'
      - 'renovate.json'

permissions:
  contents: read
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  renovate:
    name: Renovate Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
