name: Renovate

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug
          - trace
  
  # Scheduled runs
  schedule:
    # Run every Monday at 06:00 UTC (07:00/08:00 Berlin time depending on DST)
    - cron: '0 6 * * 1'
  
  # Run on pushes to renovate config
  push:
    paths:
      - '.github/workflows/renovate.yml'
      - 'renovate.json'
      - '.renovaterc.json'

env:
  # This should be set as a repository secret
  RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
  LOG_LEVEL: ${{ inputs.logLevel || 'info' }}

jobs:
  renovate:
    name: Renovate Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: ${{ env.LOG_LEVEL }}
          RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'
          RENOVATE_PLATFORM: 'github'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_USERNAME: 'renovate[bot]'
          RENOVATE_GIT_AUTHOR_NAME: 'Renovate Bot'
          RENOVATE_GIT_AUTHOR_EMAIL: 'bot@renovateapp.com'
